import {
  Apple,
  Beef,
  Beer,
  CakeSlice,
  Cherry,
  Clock,
  Coffee,
  Cookie,
  Croissant,
  CupSoda,
  Dessert,
  Drumstick,
  EggFried,
  Fish,
  Flame,
  Globe,
  Heart,
  IceCreamCone,
  Image,
  Images,
  Info,
  Leaf,
  type LucideIcon,
  MapPin,
  Martini,
  Megaphone,
  PanelBottom,
  PanelTop,
  Pizza,
  Salad,
  Sandwich,
  Share2,
  Soup,
  Sparkles,
  Star,
  Sun,
  Utensils,
  Wheat,
  Wine,
  LayoutGrid,
} from 'lucide-react';

/** Lucide icons referenced by name from data (sections, menu icons). */
export const ICONS_BY_NAME: Record<string, LucideIcon> = {
  utensils: Utensils,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  martini: Martini,
  'cup-soda': CupSoda,
  'cake-slice': CakeSlice,
  dessert: Dessert,
  'ice-cream-cone': IceCreamCone,
  cookie: Cookie,
  croissant: Croissant,
  pizza: Pizza,
  salad: Salad,
  sandwich: Sandwich,
  soup: Soup,
  'egg-fried': EggFried,
  fish: Fish,
  beef: Beef,
  drumstick: Drumstick,
  apple: Apple,
  cherry: Cherry,
  wheat: Wheat,
  leaf: Leaf,
  heart: Heart,
  star: Star,
  flame: Flame,
  sun: Sun,
  clock: Clock,
  globe: Globe,
  'map-pin': MapPin,
  image: Image,
  images: Images,
  info: Info,
  megaphone: Megaphone,
  'panel-top': PanelTop,
  'panel-bottom': PanelBottom,
  'share-2': Share2,
  sparkles: Sparkles,
};

export const MENU_ICON_SUGGESTIONS = ['utensils', 'coffee', 'wine', 'beer', 'martini', 'cup-soda', 'cake-slice', 'pizza', 'salad', 'soup', 'croissant', 'egg-fried'];

export function iconByName(name: string | undefined | null, fallback: LucideIcon = LayoutGrid): LucideIcon {
  if (!name) return fallback;
  return ICONS_BY_NAME[name.trim().toLowerCase()] ?? fallback;
}
