/**
 * Curated Lucide icon names available to the owner (menu icons, "about" features).
 * Both the site (static imports, tree-shaken) and the admin (icon picker) use this list,
 * so the public bundle never has to ship the whole icon set.
 */
export interface IconOption {
  name: string;
  label: string;
  group: 'Еда' | 'Напитки' | 'Заведение' | 'Общее';
}

export const ICON_OPTIONS: IconOption[] = [
  { name: 'utensils', label: 'Приборы', group: 'Еда' },
  { name: 'utensils-crossed', label: 'Скрещённые приборы', group: 'Еда' },
  { name: 'chef-hat', label: 'Колпак повара', group: 'Еда' },
  { name: 'soup', label: 'Суп', group: 'Еда' },
  { name: 'salad', label: 'Салат', group: 'Еда' },
  { name: 'sandwich', label: 'Сэндвич', group: 'Еда' },
  { name: 'pizza', label: 'Пицца', group: 'Еда' },
  { name: 'egg-fried', label: 'Яичница', group: 'Еда' },
  { name: 'egg', label: 'Яйцо', group: 'Еда' },
  { name: 'croissant', label: 'Круассан', group: 'Еда' },
  { name: 'cookie', label: 'Печенье', group: 'Еда' },
  { name: 'cake', label: 'Торт', group: 'Еда' },
  { name: 'cake-slice', label: 'Кусок торта', group: 'Еда' },
  { name: 'dessert', label: 'Десерт', group: 'Еда' },
  { name: 'donut', label: 'Пончик', group: 'Еда' },
  { name: 'ice-cream-cone', label: 'Мороженое', group: 'Еда' },
  { name: 'candy', label: 'Конфета', group: 'Еда' },
  { name: 'popcorn', label: 'Попкорн', group: 'Еда' },
  { name: 'beef', label: 'Мясо', group: 'Еда' },
  { name: 'drumstick', label: 'Курица', group: 'Еда' },
  { name: 'ham', label: 'Ветчина', group: 'Еда' },
  { name: 'fish', label: 'Рыба', group: 'Еда' },
  { name: 'wheat', label: 'Пшеница', group: 'Еда' },
  { name: 'vegan', label: 'Веган', group: 'Еда' },
  { name: 'leaf', label: 'Лист', group: 'Еда' },
  { name: 'sprout', label: 'Росток', group: 'Еда' },
  { name: 'carrot', label: 'Морковь', group: 'Еда' },
  { name: 'apple', label: 'Яблоко', group: 'Еда' },
  { name: 'banana', label: 'Банан', group: 'Еда' },
  { name: 'cherry', label: 'Вишня', group: 'Еда' },
  { name: 'grape', label: 'Виноград', group: 'Еда' },
  { name: 'citrus', label: 'Цитрус', group: 'Еда' },
  { name: 'flame', label: 'Огонь / острое', group: 'Еда' },
  { name: 'coffee', label: 'Кофе', group: 'Напитки' },
  { name: 'cup-soda', label: 'Лимонад', group: 'Напитки' },
  { name: 'glass-water', label: 'Вода', group: 'Напитки' },
  { name: 'milk', label: 'Молоко', group: 'Напитки' },
  { name: 'wine', label: 'Вино', group: 'Напитки' },
  { name: 'beer', label: 'Пиво', group: 'Напитки' },
  { name: 'martini', label: 'Коктейль', group: 'Напитки' },
  { name: 'hop', label: 'Хмель', group: 'Напитки' },
  { name: 'home', label: 'Дом', group: 'Заведение' },
  { name: 'map-pin', label: 'Адрес', group: 'Заведение' },
  { name: 'clock', label: 'Часы', group: 'Заведение' },
  { name: 'timer', label: 'Таймер', group: 'Заведение' },
  { name: 'calendar', label: 'Календарь', group: 'Заведение' },
  { name: 'phone', label: 'Телефон', group: 'Заведение' },
  { name: 'mail', label: 'Почта', group: 'Заведение' },
  { name: 'wifi', label: 'Wi-Fi', group: 'Заведение' },
  { name: 'sofa', label: 'Диван', group: 'Заведение' },
  { name: 'armchair', label: 'Кресло', group: 'Заведение' },
  { name: 'lamp', label: 'Лампа', group: 'Заведение' },
  { name: 'tv', label: 'Телевизор', group: 'Заведение' },
  { name: 'music', label: 'Музыка', group: 'Заведение' },
  { name: 'music-2', label: 'Нота', group: 'Заведение' },
  { name: 'camera', label: 'Камера', group: 'Заведение' },
  { name: 'car', label: 'Парковка / авто', group: 'Заведение' },
  { name: 'bike', label: 'Велосипед', group: 'Заведение' },
  { name: 'truck', label: 'Доставка', group: 'Заведение' },
  { name: 'shopping-bag', label: 'На вынос', group: 'Заведение' },
  { name: 'credit-card', label: 'Карта', group: 'Заведение' },
  { name: 'banknote', label: 'Наличные', group: 'Заведение' },
  { name: 'users', label: 'Компания', group: 'Заведение' },
  { name: 'baby', label: 'Дети', group: 'Заведение' },
  { name: 'dog', label: 'С питомцами', group: 'Заведение' },
  { name: 'accessibility', label: 'Доступная среда', group: 'Заведение' },
  { name: 'cigarette-off', label: 'Не курят', group: 'Заведение' },
  { name: 'tree-pine', label: 'Терраса', group: 'Заведение' },
  { name: 'flower-2', label: 'Цветок', group: 'Заведение' },
  { name: 'heart', label: 'Сердце', group: 'Общее' },
  { name: 'star', label: 'Звезда', group: 'Общее' },
  { name: 'sparkles', label: 'Искры', group: 'Общее' },
  { name: 'award', label: 'Награда', group: 'Общее' },
  { name: 'thumbs-up', label: 'Класс', group: 'Общее' },
  { name: 'smile', label: 'Улыбка', group: 'Общее' },
  { name: 'gift', label: 'Подарок', group: 'Общее' },
  { name: 'percent', label: 'Скидка', group: 'Общее' },
  { name: 'tag', label: 'Ценник', group: 'Общее' },
  { name: 'party-popper', label: 'Праздник', group: 'Общее' },
  { name: 'check-circle', label: 'Галочка', group: 'Общее' },
  { name: 'shield-check', label: 'Качество', group: 'Общее' },
  { name: 'bell', label: 'Колокольчик', group: 'Общее' },
  { name: 'book-open', label: 'Книга', group: 'Общее' },
  { name: 'globe', label: 'Сайт', group: 'Общее' },
  { name: 'send', label: 'Telegram', group: 'Общее' },
  { name: 'message-circle', label: 'WhatsApp', group: 'Общее' },
  { name: 'instagram', label: 'Instagram', group: 'Общее' },
  { name: 'youtube', label: 'YouTube', group: 'Общее' },
  { name: 'sun', label: 'Солнце', group: 'Общее' },
  { name: 'sunrise', label: 'Рассвет', group: 'Общее' },
  { name: 'moon', label: 'Луна', group: 'Общее' },
  { name: 'cloud-sun', label: 'Погода', group: 'Общее' },
  { name: 'snowflake', label: 'Снежинка', group: 'Общее' },
  { name: 'umbrella', label: 'Зонт', group: 'Общее' },
];

export const ICON_NAMES: string[] = ICON_OPTIONS.map((i) => i.name);

export function isKnownIcon(name: string): boolean {
  return ICON_NAMES.includes(name.trim().toLowerCase());
}
