import {
  Accessibility,
  Apple,
  Armchair,
  Award,
  Baby,
  Banana,
  Banknote,
  Beef,
  Beer,
  Bell,
  Bike,
  BookOpen,
  Cake,
  CakeSlice,
  Calendar,
  Camera,
  Candy,
  Car,
  Carrot,
  CheckCircle,
  ChefHat,
  Cherry,
  CigaretteOff,
  Citrus,
  Clock,
  CloudSun,
  Coffee,
  Cookie,
  CreditCard,
  Croissant,
  CupSoda,
  Dessert,
  Dog,
  Donut,
  Drumstick,
  Egg,
  EggFried,
  Fish,
  Flame,
  Flower2,
  Gift,
  GlassWater,
  Globe,
  Grape,
  Ham,
  Heart,
  Home,
  Hop,
  IceCreamCone,
  Instagram,
  Lamp,
  Leaf,
  Mail,
  MapPin,
  Martini,
  MessageCircle,
  Milk,
  Moon,
  Music,
  Music2,
  PartyPopper,
  Percent,
  Phone,
  Pizza,
  Popcorn,
  Salad,
  Sandwich,
  Send,
  ShieldCheck,
  ShoppingBag,
  Smile,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Sunrise,
  Tag,
  ThumbsUp,
  Timer,
  TreePine,
  Truck,
  Tv,
  Umbrella,
  Users,
  Utensils,
  UtensilsCrossed,
  Vegan,
  Wheat,
  Wifi,
  Wine,
  Youtube,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

/**
 * Icons the owner can pick in the admin (see ICON_OPTIONS in @merenda/shared).
 * Statically imported so the bundle only carries this curated set.
 */
const ICONS: Record<string, LucideIcon> = {
  'utensils': Utensils,
  'utensils-crossed': UtensilsCrossed,
  'chef-hat': ChefHat,
  'soup': Soup,
  'salad': Salad,
  'sandwich': Sandwich,
  'pizza': Pizza,
  'egg-fried': EggFried,
  'egg': Egg,
  'croissant': Croissant,
  'cookie': Cookie,
  'cake': Cake,
  'cake-slice': CakeSlice,
  'dessert': Dessert,
  'donut': Donut,
  'ice-cream-cone': IceCreamCone,
  'candy': Candy,
  'popcorn': Popcorn,
  'beef': Beef,
  'drumstick': Drumstick,
  'ham': Ham,
  'fish': Fish,
  'wheat': Wheat,
  'vegan': Vegan,
  'leaf': Leaf,
  'sprout': Sprout,
  'carrot': Carrot,
  'apple': Apple,
  'banana': Banana,
  'cherry': Cherry,
  'grape': Grape,
  'citrus': Citrus,
  'flame': Flame,
  'coffee': Coffee,
  'cup-soda': CupSoda,
  'glass-water': GlassWater,
  'milk': Milk,
  'wine': Wine,
  'beer': Beer,
  'martini': Martini,
  'hop': Hop,
  'home': Home,
  'map-pin': MapPin,
  'clock': Clock,
  'timer': Timer,
  'calendar': Calendar,
  'phone': Phone,
  'mail': Mail,
  'wifi': Wifi,
  'sofa': Sofa,
  'armchair': Armchair,
  'lamp': Lamp,
  'tv': Tv,
  'music': Music,
  'music-2': Music2,
  'camera': Camera,
  'car': Car,
  'bike': Bike,
  'truck': Truck,
  'shopping-bag': ShoppingBag,
  'credit-card': CreditCard,
  'banknote': Banknote,
  'users': Users,
  'baby': Baby,
  'dog': Dog,
  'accessibility': Accessibility,
  'cigarette-off': CigaretteOff,
  'tree-pine': TreePine,
  'flower-2': Flower2,
  'heart': Heart,
  'star': Star,
  'sparkles': Sparkles,
  'award': Award,
  'thumbs-up': ThumbsUp,
  'smile': Smile,
  'gift': Gift,
  'percent': Percent,
  'tag': Tag,
  'party-popper': PartyPopper,
  'check-circle': CheckCircle,
  'shield-check': ShieldCheck,
  'bell': Bell,
  'book-open': BookOpen,
  'globe': Globe,
  'send': Send,
  'message-circle': MessageCircle,
  'instagram': Instagram,
  'youtube': Youtube,
  'sun': Sun,
  'sunrise': Sunrise,
  'moon': Moon,
  'cloud-sun': CloudSun,
  'snowflake': Snowflake,
  'umbrella': Umbrella,
};

export interface IconProps extends LucideProps {
  name: string;
  fallback?: LucideIcon;
}

export function Icon({ name, fallback: Fallback = Sparkles, ...props }: IconProps) {
  const key = name.trim().toLowerCase();
  const Cmp = ICONS[key] ?? Fallback;
  return <Cmp {...props} />;
}
